### ISSUE TITLE
Question, can we scrape icons from pull-request the feather repo

### ISSUE THREAD

**Issue by ericfennis** [featherity/featherity#11]
There are stil some great icons waiting to be merged in the feather repo.
Do you think we can just take their code and contribute it to this repo? 🤔 
Or do we need to ask them to do that.
For example the [#813](https://github.com/feathericons/feather/pull/813), the dice icon look cool to me.

**Comment by jletey** [comment]
Although it is possible, it is morally wrong to take peoples work and call it our own!

By all means if you want to see an icon in @featherity, by all means go to the PRs and ask the people that opened them to open one here 😄

**Comment by ericfennis** [comment]
Yeah don't want to call it my own. But maybe we can mention them in pull-request?

**Comment by locness3** [comment]
Well, feather itself is under MIT, and so the forks are, so technically we can use them.

**Comment by jletey** [comment]
Very true, btw can someone review #12?

**Comment by ericfennis** [comment]
@locness3 gave the answer. Let's mention them if use some of those icons
