### ISSUE TITLE
Icon request: intermediate battery levels

### ISSUE THREAD

**Issue by fabricedesre** [featherity/featherity#22]
## Icon Request

* Icon name: battery-25, battery-50, battery-75, battery-full and -charging versions.
* Use case: There are currently 2 battery icons: one when plugged in ("battery-charging") and the regular "battery". It would be nice to be able to indicate the charge level as well. 0 (available currently), 25%, 50%, 75% and full should be enough.
* Screenshots of similar icons:

**Comment by jletey** [comment]
@fabricedesre At the moment there is already `battery` and `battery-charging` icons:

<img width="335" alt="Screenshot 2020-06-23 at 19 27 32" src="https://user-images.githubusercontent.com/62398724/85442182-ce070380-b587-11ea-96cc-b7a3df2f39b7.png">

Also https://github.com/feathericons/feather/pull/172 might be useful. I can take this on 👍

**Comment by fabricedesre** [comment]
Yes https://github.com/feathericons/feather/pull/172#issuecomment-513655006 look great!

**Comment by ericfennis** [comment]
@jletey maybe also try to implement the "safe-zone" of 1px (if it looks nice of course). Correct if I'm wrong but the current battery icons don't uses the safe-zone right now.

**Comment by jletey** [comment]
@ericfennis Completely agree will do that!
