### ISSUE TITLE
Icon request: start/stop sharing screen

### ISSUE THREAD

**Issue by dgdavid** [featherity/featherity#26]
Hi there!

First of all, **thank you a lot** for the initiative to, somehow, _moving forward_ the [Feather](https://github.com/feathericons/feather) project. I really hope the effort and result can convince @colebemis  about [his concerns](https://github.com/feathericons/feather/issues/893#issuecomment-617463032) and see both project meet in the near future.

That said, my request is an icon for the "Screen sharing" action in a video conferencing software. Back in April, I was trying to do it but my lack of design / SVG / Figma knowledge didn't allow me to make something presentable. Even after spending quite some hours! Quite frustrating :)

However, just in case it could be helpful, I can tell you that I don't like too much the one [included in the Material Design icons](https://material.io/resources/icons/?icon=screen_share&style=baseline). Maybe, something similar to https://thenounproject.com/search/?q=screen%20share&i=2012801 or https://thenounproject.com/tomekpst/collection/basic-icons/?i=2012799 but based the [Feather/monitor](https://feathericons.com/?query=monitor) could look nice.

On the other hand, using the [Feather/wifi](https://feathericons.com/?query=wifi) or [Feather/rss](https://feathericons.com/?query=rss) icon as part of it instead of the arrow could be confusing because it seems to be more appropriate for an "screen-casting" action, isn't it?

What do you think? Could it be possible to have _feather-style_ icons for start / stop sharing the screen?

Thanks in advance.

## Icon Request

* Icon name: start-screen-sharing, stop-screen-sharing
* Use case: for a video conferencing software
* Screenshots of similar icons:

  |||
  |-|-|
  | ![Screenshot_2020-06-26 Noun Project](https://user-images.githubusercontent.com/1691872/85857033-f9b90200-b7b0-11ea-9c1c-32a30f884512.png) | ![Screenshot_2020-06-26 Noun Project(1)](https://user-images.githubusercontent.com/1691872/85857046-ffaee300-b7b0-11ea-9b0c-a0effe42c719.png) |

**Comment by jletey** [comment]
> **thank you a lot** for the initiative to, somehow, _moving forward_ the [Feather](https://github.com/feathericons/feather) project.

Thank you for the kind words. The amazing community and I didn't want the project to die, so we took matters into our own hands!

> Could it be possible to have _feather-style_ icons for start / stop sharing the screen?

Yes! More than definitely possible!

I love your suggestions, and I will design some feather-style icons now.
