### ISSUE TITLE
Icons request: flashlight

### ISSUE THREAD

**Issue by fabricedesre** [featherity/featherity#30]
## Icon Request

* Icon name: flashlight in on on/off state.
* Use case: quite obvious :)
* Screenshots of similar icons: they are not really nice, but there is  https://fontawesome.com/icons?d=gallery&q=flashlight

**Comment by jletey** [comment]
@fabricedesre Something like [this](https://fontawesome.com/icons/flashlight?style=light)?

<img width="1376" alt="Screenshot 2020-06-28 at 08 49 17" src="https://user-images.githubusercontent.com/62398724/85941705-43722b80-b91c-11ea-92d7-07ff81a39079.png">

**Comment by fabricedesre** [comment]
Yes, that's the one I linked to. Some also show a "light beam" for the "flashlight on" version

**Comment by ericfennis** [comment]
Maybe something like this? ![Screenshot_20200630-132156.jpg](https://user-images.githubusercontent.com/11825403/86120585-dfdf2e00-bad4-11ea-92bd-d1933179b318.jpg)

**Comment by ericfennis** [comment]
I tried to make some designs.
![image](https://user-images.githubusercontent.com/11825403/86519360-734c9200-be3a-11ea-8a8a-673fac51d6ca.png)

**Comment by jletey** [comment]
I like the last two 🔥 What about when it's switched on?

**Comment by ericfennis** [comment]
I think this one should be the "switched on variant". And we can also make a "off" variant, with a slash like the `wifi-off` icon.

**Comment by jletey** [comment]
Sounds good, but ask @fabricedesre 😄

**Comment by fabricedesre** [comment]
Fine for me! I'm not a designer, so I trust you guys on how to best convey the meaning!

**Comment by ericfennis** [comment]
I think the right one fits the best.
